"""initial schema

Revision ID: 242ababd63b4
Revises:
Create Date: 2026-09-24 16:44:17.379964
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "242ababd63b4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "research_projects",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("product_description", sa.Text(), nullable=False),
        sa.Column("target_audience", sa.Text(), nullable=False),
        sa.Column("research_goal", sa.Text(), nullable=False),
        sa.Column("num_personas", sa.Integer(), nullable=False),
        sa.Column("num_questions", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("model_used", sa.String(length=120), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("research_projects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_projects_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_research_projects_status"), ["status"], unique=False)

    op.create_table(
        "insight_reports",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("executive_summary", sa.Text(), nullable=False),
        sa.Column("overall_sentiment", sa.String(length=10), nullable=False),
        sa.Column("notable_quotes", sa.JSON(), nullable=False),
        sa.Column("weak_areas_or_risks", sa.JSON(), nullable=False),
        sa.Column("recommendations", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("insight_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_insight_reports_project_id"), ["project_id"], unique=True
        )

    op.create_table(
        "personas",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("occupation", sa.String(length=255), nullable=False),
        sa.Column("background", sa.Text(), nullable=False),
        sa.Column("personality_traits", sa.JSON(), nullable=False),
        sa.Column("behavioral_patterns", sa.JSON(), nullable=False),
        sa.Column("psychological_profile", sa.Text(), nullable=False),
        sa.Column("goals", sa.JSON(), nullable=False),
        sa.Column("pain_points", sa.JSON(), nullable=False),
        sa.Column("tech_savviness", sa.String(length=10), nullable=False),
        sa.Column("communication_style", sa.String(length=255), nullable=False),
        sa.Column("persona_summary", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("personas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_personas_project_id"), ["project_id"], unique=False)

    op.create_table(
        "survey_questions",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=30), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("survey_questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_survey_questions_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "conversations",
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_persona_id"), ["persona_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "survey_responses",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("persona_slug", sa.String(length=60), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("sentiment", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["survey_questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("survey_responses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_survey_responses_persona_slug"), ["persona_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_survey_responses_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_survey_responses_question_id"), ["question_id"], unique=False
        )

    op.create_table(
        "themes",
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("prevalence", sa.String(length=10), nullable=False),
        sa.Column("supporting_persona_ids", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["insight_reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("themes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_themes_report_id"), ["report_id"], unique=False)

    op.create_table(
        "conversation_messages",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_conversation_id"),
            ["conversation_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_messages_conversation_id"))

    op.drop_table("conversation_messages")
    with op.batch_alter_table("themes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_themes_report_id"))

    op.drop_table("themes")
    with op.batch_alter_table("survey_responses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_survey_responses_question_id"))
        batch_op.drop_index(batch_op.f("ix_survey_responses_project_id"))
        batch_op.drop_index(batch_op.f("ix_survey_responses_persona_slug"))

    op.drop_table("survey_responses")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_project_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_persona_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("survey_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_survey_questions_project_id"))

    op.drop_table("survey_questions")
    with op.batch_alter_table("personas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_personas_project_id"))

    op.drop_table("personas")
    with op.batch_alter_table("insight_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insight_reports_project_id"))

    op.drop_table("insight_reports")
    with op.batch_alter_table("research_projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_projects_status"))
        batch_op.drop_index(batch_op.f("ix_research_projects_owner_id"))

    op.drop_table("research_projects")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
